# Generated by Django 3.2.6 on 2024-06-22 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_tag_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='midified_at',
            new_name='modified_at',
        ),
    ]
