remote_theme: just-the-docs/just-the-docs

description: A Jekyll theme for documentation
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://just-the-docs.com" # the base hostname & protocol for your site, e.g. http://example.com
repository: just-the-docs/just-the-docs # for github-metadata

permalink: pretty

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
